plugins {
    id 'java'
    id 'maven-publish'
}

group = 'dev.zeith.lzvm.molang'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":")

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation 'com.google.code.gson:gson:2.11.0'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.register('sourcesJar', Jar) {
    dependsOn classes
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = lzVmBaseGroup
            artifactId = 'MoLang'

            from components.java
            artifact tasks.sourcesJar

            pom {
                name = 'MoLang'
                description = 'MoLang support for LzVM.'
            }
        }
    }

    repositories {
        maven {
            url System.env.MAVEN_URL
        }
    }
}