plugins {
    id 'java'
}

group = 'dev.zeith.lzvm.molang'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":")

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation 'com.google.code.gson:gson:2.11.0'
}

tasks.named('test') {
    useJUnitPlatform()
}