description = 'MoLang support for LzVM.'

dependencies {
    implementation project(":")

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation 'com.google.code.gson:gson:2.11.0'
}

tasks.named('test') {
    useJUnitPlatform()
}

mavenPublishing {
    publishToMavenCentral()

    signAllPublications()
    coordinates(group, 'MoLang', version)

    pom {
        name = 'MoLang'
        description = 'MoLang support for LzVM.'
        url = 'https://github.com/ZeithLibs/LzVM'

        licenses {
            license {
                name = 'Zeith Standard Free License'
                url = 'https://zeith.dev/license/zsfl'
            }
        }

        scm {
            connection = 'scm:git:git://github.com/ZeithLibs/LzVM.git'
            developerConnection = 'scm:git:ssh://git@github.com/ZeithLibs/LzVM.git'
            url = 'https://github.com/ZeithLibs/LzVM'
        }

        developers {
            developer {
                id = 'zeith'
                name = 'Zeith'
            }
        }
    }
}