plugins {
    id 'java'
}

group = 'dev.zeith.lzvm'
version = lzVmVersion

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(javaVersion)
        }
    }

    dependencies {
        compileOnly "org.projectlombok:lombok:$lombok"
        annotationProcessor "org.projectlombok:lombok:$lombok"
        implementation("org.jetbrains:annotations:$jbAnnotation")
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(javaVersion)
    }
}

repositories {
    mavenCentral()
//    maven {
//        url = "https://maven.zeith.org"
//    }
}

dependencies {
    compileOnly "org.projectlombok:lombok:$lombok"
    annotationProcessor "org.projectlombok:lombok:$lombok"

    implementation("org.ow2.asm:asm:$owasm")
    implementation("org.ow2.asm:asm-tree:$owasm")
    implementation("org.jetbrains:annotations:$jbAnnotation")
}
